all: ComposedClass SuperclassExample InterfaceExample Example
	

ComposedClass: ComposedClass.java 
	javac ComposedClass.java 

SuperclassExample: SuperclassExample.java
	javac SuperclassExample.java 

InterfaceExample: InterfaceExample.java
	javac InterfaceExample.java 

Example: Example.java
	javac Example.java 

.PHONY: clean

clean:
	rm ComposedClass.class SuperclassExample.class InterfaceExample.class Example.class
